name: 'Docureco Agent: Baseline Map Creator'

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to analyze'
        required: true
        default: 'main'
      force_recreate:
        description: 'Force recreate if baseline map exists'
        required: false
        default: false
        type: boolean

env:
  # LLM Configuration
  GROK_API_KEY: ${{ secrets.GROK_API_KEY }}
  GROK_BASE_URL: ${{ secrets.GROK_BASE_URL }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  OPENAI_BASE_URL: ${{ vars.OPENAI_BASE_URL }}
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
  
  DOCURECO_LLM_PROVIDER: ${{ vars.DOCURECO_LLM_PROVIDER }}
  DOCURECO_LLM_MODEL: ${{ vars.DOCURECO_LLM_MODEL }}
  DOCURECO_LLM_TEMPERATURE: ${{ vars.DOCURECO_LLM_TEMPERATURE }}
  DOCURECO_LLM_MAX_TOKENS: ${{ vars.DOCURECO_LLM_MAX_TOKENS }}
  DOCURECO_LLM_MAX_RETRIES: ${{ vars.DOCURECO_LLM_MAX_RETRIES }}
  DOCURECO_LLM_TIMEOUT: ${{ vars.DOCURECO_LLM_TIMEOUT }}

  MAX_CONCURRENT_OPERATIONS: ${{ vars.MAX_CONCURRENT_OPERATIONS }}

  # LangSmith Configuration
  LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
  
  # Database Configuration
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
  SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
  
  # GitHub Configuration
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  # Logging
  LOG_LEVEL: ${{ vars.LOG_LEVEL || 'INFO' }}

jobs:
  create-baseline-map:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: 'agent/requirements.txt'
    
    - name: Set up Node.js (for Repomix)
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install Repomix
      run: |
        npm install -g repomix
        repomix --version
    
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('agent/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r agent/requirements.txt
        
    - name: Validate inputs
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.event.inputs.branch }}"
        echo "Force recreate: ${{ github.event.inputs.force_recreate }}"
    
    - name: Create baseline traceability map
      env:
        LOG_LEVEL: 'INFO'
      run: |
        python -m agent baseline-map-creator \
          ${{ github.repository }} \
          --branch ${{ github.event.inputs.branch }} \
          ${{ github.event.inputs.force_recreate == 'true' && '--force' || '' }} \
          --log-level INFO

    - name: Sanitize artifact name
      run: |
        repo_name="${{ github.repository }}"
        branch_name="${{ github.event.inputs.branch }}"
        echo "ARTIFACT_NAME=baseline-map-${repo_name//\//_}-${branch_name//\//_}" >> $GITHUB_ENV
    
    - name: Upload baseline map artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: |
          agent/logs/
          agent/output/
          *.log
        retention-days: 90
    
    - name: Create summary
      if: always()
      run: |
        echo "## 📊 Baseline Map Creation Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Repository:** \`${{ github.repository }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Branch:** \`${{ github.event.inputs.branch }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Force Recreate:** \`${{ github.event.inputs.force_recreate }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Status:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 🔗 Workflow Details" >> $GITHUB_STEP_SUMMARY
        echo "- Started by: @${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
        echo "- Workflow: ${{ github.workflow }}" >> $GITHUB_STEP_SUMMARY
        echo "- Run ID: ${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY 